services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exam_system_sql
    user: root
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!QW
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - exam-network

  api:
    build:
      context: .
      dockerfile: ExamSystem.API/Dockerfile
    container_name: exam_system_api
    ports:
      - "8080:8080"
    environment:
      - Database__ConnectionString=Server=sqlserver;Database=ExamSystemDb;User Id=sa;Password=Password123!QW;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      sqlserver:
        condition: service_started
    networks:
      - exam-network

  web:
    build:
      context: .
      dockerfile: ExamSystem.Web/Dockerfile
    container_name: exam_system_web
    ports:
      - "5246:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Api__BaseUrl=http://exam_system_api:8080
    depends_on:
      - api
    networks:
        - exam-network

networks:
  exam-network:
    driver: bridge

volumes:
  mssql_data: